apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: sample-app
 namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: stage
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-sample-app'
      namespace: openshift-gitops
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-enablement/sample-app-manifests
        targetRevision: main
        path: application/sample-app
      destination:
        server: '{{url}}'
        namespace: sample-app-{{cluster}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true